### ISSUE TITLE
Null Pointer Exception in bitmapview 

### ISSUE THREAD

**Issue by NandinireddyM** [rahul357/FaceCropper-FaceDetectionAPi#1]
Caused by: java.lang.NullPointerException
                                                                             at in.doomers.imagecropper.BitmapView.logFaceData(BitmapView.java:190)
                                                                             at in.doomers.imagecropper.BitmapView.setBitmap(BitmapView.java:79)
                                                                             at in.doomers.imagecropper.MainActivity.onCreate(MainActivity.java:30)
                                                                             at android.app.Activity.performCreate(Activity.java:5248)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2173)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2269) 
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:139) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:136) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5102) 
                                                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                             at dalvik.system.NativeStart.main(Native Method)

**Comment by doomers** [comment]
can you exactly tell me what exactly caused this error so i can resolve this as early as possible. As application is working perfectly in my device.
